name: 🤖 Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo '### head info'
          git log -1
          
          echo '### split upm branch'
          git subtree split -P "$PKG_ROOT" -b upm
          
          echo '### update remote branch'
          git checkout upm
          git push -f -u origin upm
        env:
          PKG_ROOT: pixel-finder/
